
#define BUFFER  ( 0x2000  )
#define INITIAL_STACK  ( 0x2000  )
#define SECOND_STACK  ( 0x80000  )
#define KERNEL_LOADER  ( 0x8000  )
#define KERNEL_LOADER_SEC_NUM  ( 0x38  )
#define KERNEL_LOADER_SECOND_SEC_NUM  ( 0x2  )
#define KERNEL_LOADER_SECOND  ( 0x1000  )
#define KERNEL_LOADER_ELF_OFFSET  ( KERNEL_LOADER  )

#define CODE_SEG  ( 0x08  )
#define DATA_SEG  ( 0x10  )

#define KERNEL_ADD  ( 0x100000  )

#define INTERRUPT_TABLE_64  ( 0x6000  )
#define INTERRUPT_TABLE_64_SIZE  ( 0x1000  )

#define INTERRUPT_TABLE_32  ( INTERRUPT_TABLE_64 + INTERRUPT_TABLE_64_SIZE  )
#define INTERRUPT_TABLE_32_SIZE  ( 0x800  )




#define MEMORY_MAP_BUFFER1  ( INTERRUPT_TABLE_32 + INTERRUPT_TABLE_32_SIZE  )
#define MEMORY_MAP_BUFFER_ENTRY_SIZE  ( 8*3  )
#define MEMORY_MAP_BUFFER_MAX_ENTRIES  ( 16  )
#define MEMORY_MAP_BUFFER_SIZE  ( MEMORY_MAP_BUFFER_ENTRY_SIZE * MEMORY_MAP_BUFFER_MAX_ENTRIES  )
#define MEMORY_MAP_MAGIC  ( 0x534D4150  )



#define GDT_LOCATION  ( MEMORY_MAP_BUFFER1 + MEMORY_MAP_BUFFER_SIZE  )
#define GDT_SIZE  ( 5*8  )



#define GLOBALS  ( 0x7a00  )


#define GPT_HEADER  ( BUFFER  )
#define GPT_HEADER_SIZE  ( 92  )
#define GPT_HEADER_PARTITION_ENTRY_SIZE_OFFSET  ( 84  )
#define GPT_HEADER_PARTITION_ENTRY_NUMBER_OFFSET  ( 80  )
#define GPT_HEADER_SEGMENT_SIZE  ( 512  )



#define GPT_PARTITION_ENTRY_BUFF  ( BUFFER + GPT_HEADER_SEGMENT_SIZE  )
#define GPT_PARTITION_ENTRY_SIZE_LIMIT  ( 128  )
#define GPT_PARTITION_ENTRY_BUFF_NAME_OFFSET  ( 0x38  )
#define MAX_ENTRIES  ( 0x10  )
#define GPT_PARTITION_ENTRY_BUFF_LEN  ( GPT_PARTITION_ENTRY_SIZE_LIMIT * MAX_ENTRIES  )















